### ISSUE TITLE
v0.12.0 checklist

### ISSUE THREAD

**Issue by jondot** [loco-rs/loco#915]
* [ ] new loco-gen
* [ ] new loco-cli
* [ ] new starters
* [ ] changelog
* [ ] docs updates per changelog items
